### ISSUE TITLE
Highlight function to compare trees is not working

### ISSUE THREAD

**Issue by tv195** [DessimozLab/phylo-io#4]
The feature
" For interactive analysis of specific parts of the tree, the user can select a node and highlight it. The best corresponding node in the opposing tree is then highlighted and centered, allowing the user to interactively match structures within the compared trees."
doesn't seem to work. One can click on a clad, select highlight, but nothing is shown in the corresponding tree in the other panel

**Comment by phylo-io** [comment]
Is this still a problem, testing with the current production and dev versions highlight the node at least with the example trees. Can you provide or share example trees that shows the error.
