### ISSUE TITLE
problem - share button

### ISSUE THREAD

**Issue by ijulca** [DessimozLab/phylo-io#7]
I can't see the share button when I open phylo-io in chrome or mozilla.

**Comment by cdessimoz** [comment]
Sorry about this. We introduced this bug very recently. Meanwhile, I have restored an older release on phylo.io (commit df0695a19c095d5e1f224b529bb1edb0dd4aaa75) and the share button works again. We will fix this asap.

**Comment by ijulca** [comment]
thank you!
