### ISSUE TITLE
Starting phlo-io on localhost

### ISSUE THREAD

**Issue by omerkaramanli** [DessimozLab/phylo-io#9]
Hello, 

I am trying to use your source code for my own project and add&modify some stuff. But I am stuck at the beginning. I have downloaded all your code and opened its file on Visual Studio Code, when I try to run it with ```npm run dev``` nothing happens. 

I have tried following the steps in [this](https://blogs.msdn.microsoft.com/cdndevs/2016/01/24/visual-studio-code-and-local-web-server/) and at the end I am left with 

![image](https://user-images.githubusercontent.com/41186416/68114711-bfd87a00-ff07-11e9-8346-882a3cd5a895.png)

My question is, can you help me run your project in my localhost?

**Comment by Nrde** [comment]
You don't need a webserver to run phylo.io locally on your machine. You only need a browser.

drag and drop /www/index.html to your browser and there you have it.

**Comment by omerkaramanli** [comment]
Thank you so much. 

I have a couple more questions.

1- If I wanted to add more features on the menu which appears on the screen when a node is selected, where should I do those changes and updates? 
2- If I wanted to do a multi select on nodes in a tree, how would you propose I do that?

**Comment by Nrde** [comment]
You can see some code that adds menuitems to nodes starting around line 5325 on master branch.

It would require a lot of work to do multiselect and it would depend on the task you would like to do with those nodes. maybe it would be just easier to remove extra nodes from the tree beforehand.

**Comment by omerkaramanli** [comment]
Hello, It's been a while.

Right now, I have added some options to do multi selecting. With a code like this:

     var multiSelected = [] //as global variable, at the top of the TreeCompare function

     if(!multiSelected[0]){
          add_menu_item(".tooltipElem",
               function(){
                    return 'Select as first >'
               },
               function(){
                   d.select(this).style("fill", "yellow")
                   multiSelected.push(d);
               }
           );
      };

There is also a select as second function. Right now, what I want to do is, color those nodes which were selected as first and second. 

Do you have any suggestions on how I can do these?
What I've tried so far to color are:

-
          d.color("yellow");
- 
          d3.select(this).on("mouseclick", function(d) {
               d3.select(this).transition().style("fill", "yellow").style("cursor", "pointer");
          });
-
          d3.select(this).style("fill", "yellow");
-
          d3.select("#" + d.ID).classed("select", true);

Nothing worked so far. 

I know, I'm doing a guess work to make it work but I dont know how can I make it work. I mean, I simply copy your code for highlighting but it does not work.

Thank you in advance.
